version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "monthly"

  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
      time: "16:00"
      timezone: Australia/Melbourne
    rebase-strategy: "auto"
    labels:
      - "security"
      - "dependencies"
    open-pull-requests-limit: 10